POST http://localhost:8080/order
Content-Type: application/json
Accept: application/json

{
"apples": 10,
"oranges": 10
}

###
POST http://localhost:8080/order
Content-Type: application/json
Accept: application/json

{
"apples": 5,
"oranges": 2
}

###
GET http://localhost:8080/order/1
Content-Type: application/json
Accept: application/json

###
GET http://localhost:8080/order/2
Content-Type: application/json
Accept: application/json

###
GET http://localhost:8080/order/all
Content-Type: application/json
Accept: application/json

